---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-login
  namespace: dev
spec:
  encryptedData:
    .dockerconfigjson: AgBiopNtcdwGaWbfgasP8JO6NK7RrC+0mCvjsNGfwi7s+xnbJ6duSS7gFE72EL4y2OxxbrkapLemdwquVrdwqy4fDeu+KCEtLrgatXNV6l9wDC6Ps3gsgw4C57AGYFenzk5J5QRDL2T1DDLrT0TOjPJtQrmf/nafFNEg88Jt1G/vh6iDCxEFA2p7AWKDK+E7zQeYb46EvbZpUjMkmyngh3dFjwiEj9mM2ddzaTMc10abmegcdAfQCMePzCSdXOdy/PxuZiQ3x0I5NMSDNB3+/PQwvuFbwJSuHLyJZhBpAUFMXzqLX7OtpygYmGaGaWLnbfnwUs8n0nEdpcIr3kHtXfjjPnciUK2lSxnWpeMIcbT8/EaBw1RKorkIKsYcUKWY8M9uEBE7VI7MlBIsmPogrS6N5ALwDlY+uneRfHfqzJONz0FBNwhv3ZkVFRFpt9Oj3Eqkwi7seVnoH35nsrAY5z/Uvg60mOcbGzWR3JOhwymfNqse97LHV2otDEde71B+ZC4sPeNEwi6NxDsVVo7oY9/Sa8aoXxwtKRXGmwqpyIDL0OWonsSIpM6XXU2KO851g6oZAx9qnhcYXPxNBq2TpP7kyyh9Xlp0lL6ZAwCYO+OJAn0WrTQbNjbxzd0Nmod2F59rqvsIbjsypSYUMLKqwOdb5sYSnBZ+vIbmakzYP4xqMO7RiuHKfLzPL7xYfpq183BJca+iCqZh7ObInkY/BXudGEKgusSv6xQtZoScuuIxq5o8WOYOd6MD4BwZ4/1ctr580JzUflZedoVjKAD/mKbE2O112HsQ+0Yin00UszqjlOsX8lLLtCeDIfwmleXWg7bC/h3GXhX85vnuKQQhAGkx4LLl4uJmx4imlF5XpFBy0eqxhegjXyLEv+guMt3sXu4qgjXkbfHwn6r817LvOn32HzRZNkg7zCAN1JmvDUqQCwRuYUZTgz1mT+7crYgV31wUlKk5XH3k
  template:
    metadata:
      name: ghcr-login
      namespace: dev
    type: kubernetes.io/dockerconfigjson
