---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-login
  namespace: dev
spec:
  encryptedData:
    .dockerconfigjson: AgAKhk0sR1E/UvWd5Ujc9rRqsbfjq6GwrBhvyLiKsU3v2ZNcaJJDgYtRNiGdK+35miNBxOYdEAecJBkZw9Plt0jUW5OSQoVt8UipP9LsHidjq9y9IlsKkkz73Ob3ES20p6bUar7+1MpVXbK7gXiKCW7cpfWkVNwy4cD5eprCvzfnjEQnvWLG49+7VHBQGDEk1gbxDoIHghuivfBLOeccCSeoc22xGhcypDIh3tAjRPx1ebYeRQrU8GF/b0v4JE5A3GXjQCKvlJrRMIY6OxaO/GxtuDw/NuGq5CVRB7T4J2soTumGqho2fR1uYsJei8n2w5VB8GrJCfWXBLNRJPQtRBOBSOSzETxxe1eBViEg8bYAO+Vt8hHWwv1ISvAfBU0zWtBgLDGlQk7NPq4m0yTKrCc2o6Erh85dV8zsr1GeGLau2E6tZoDIRL451LQNE5po/5yZZ6cEW95MVY+us6i1LUmGULk+EsXN7FwYfM/q4Qg0qLAm7QgTv4gZ6RmQKjxl0ftKbMW23VR8Z/s5C0bu0D+B9z0FNJELHpmaYHzotCyu9WYSAD7WpbXYif+YFXqOLw2MWcx9gUFnINJMLED8R2y35gg0cxG3d6v9iXfka8P3NTSPZvIZugSR8RZ52mtbLNhUG8NLnOQYnt/5/9/+RxQ0KgmmiO6idKQoFTfNcTuDQX47+viBqARi6QBSNnYUDRXXILhxTT7Fk1zd5SVaKkj2bXI3p/kNxFd2wi1SMGFGC6aIyaVycQ/Zm9USZt95g4qdnLndTIcNPUXHVh0FkmQIoGyJeP9Wj1oO9wBGKMxjQrvGqfM0mau+bl+wIhsvn3TfSM4nwI4vVSxS2d/9KD9xoBx4XjcO4hWL4F3+5lf7XNqG/jX1syjeRslREo1JOZL4WfpcrmXDNm6ewOqjswExZ3mPAJk+NIVb+XL/vCciOSiaiKTGPdyb
  template:
    metadata:
      name: ghcr-login
      namespace: dev
    type: kubernetes.io/dockerconfigjson
