apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      imagePullSecrets:
        - name: ghcr-login
      containers:
        - name: api-gateway
          image: ghcr.io/volontariapp/api-gateway:sha-9944c7e
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            runAsUser: 1001
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: OTEL_SDK_DISABLED
              value: "true"
            - name: NODE_ENV
              value: "production"
            - name: MS_USER_URL
              value: "ms-user:80"
            - name: MS_POST_URL
              value: "ms-post:80"
            - name: MS_SOCIAL_URL
              value: "ms-social:80"
            - name: MS_EVENT_URL
              value: "ms-event:80"
            - name: MS_WS_URL
              value: "ws-service:80"
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
            - name: certs-volume
              mountPath: /app/certs
              readOnly: true
      volumes:
        - name: certs-volume
          secret:
            secretName: auth-certs
        - name: tmp-volume
          emptyDir: {}
