apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-processor-social
  labels:
    app: post-processor-social
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-processor-social
  template:
    metadata:
      labels:
        app: post-processor-social
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      imagePullSecrets:
        - name: ghcr-login
      initContainers:
        - name: wait-for-db
          image: busybox:1.28
          command: ['sh', '-c', "until nc -zv ms-social-db-postgresql 5432; do echo waiting for db; sleep 2; done"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 32Mi
        - name: wait-for-redis
          image: busybox:1.28
          command: ['sh', '-c', "until nc -zv redis-master 6379; do echo waiting for redis; sleep 2; done"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 32Mi
        - name: wait-for-neo4j
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -zv neo4j 7687; do echo waiting for neo4j; sleep 2; done']
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ['ALL']
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 32Mi
      containers:
        - name: post-processor-social
          image: ghcr.io/volontariapp/post-processor-social:sha-8aa0577
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            runAsUser: 1001
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 4205
              name: http
          env:
            - name: NODE_ENV
              value: "production"
            - name: POST_PROCESSOR_BATCH_SIZE
              value: "10"
            - name: PORT
              value: "4205"
            - name: DB_HOST
              value: "ms-social-db-postgresql"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "ms-social"
            - name: DB_USERNAME
              value: "ms-social"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: ms-social-password
            - name: REDIS_HOST
              value: "redis-master"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: redis-password
            - name: NEO4J_HOST
              value: 'neo4j'
            - name: NEO4J_PORT
              value: '7687'
            - name: NEO4J_USERNAME
              value: 'neo4j'
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: neo4j-password
          resources:
            limits:
              cpu: 100m
              memory: 192Mi
            requests:
              cpu: 25m
              memory: 96Mi
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: tmp-volume
          emptyDir: {}
