apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-social
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-social
  template:
    metadata:
      labels:
        app: ms-social
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      imagePullSecrets:
        - name: ghcr-login
      containers:
        - name: ms-social
          image: ghcr.io/volontariapp/ms-social:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            runAsUser: 1001
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NODE_ENV
              value: "production"
            - name: DB_HOST
              value: "ms-social-db-postgresql"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "ms-social"
            - name: DB_USERNAME
              value: "ms-social"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: ms-social-password
            - name: MS_USER_URL
              value: "ms-user:3000"
            - name: MS_POST_URL
              value: "ms-post:3000"
            - name: MS_EVENT_URL
              value: "ms-event:3000"
            - name: MS_SOCIAL_URL
              value: "0.0.0.0:3000"
            - name: NEO4J_HOST
              value: "neo4j"
            - name: NEO4J_PORT
              value: "7687"
            - name: NEO4J_USERNAME
              value: "neo4j"
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: neo4j-password
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: tmp-volume
          emptyDir: {}
