apiVersion: v1
kind: Service
metadata:
  name: post-processor-social
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/health"
spec:
  selector:
    app: post-processor-social
  ports:
    - protocol: TCP
      port: 4205
      targetPort: 4205
      name: http
