apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - global-policies.yaml
  - ms-user.yaml
  - ms-post.yaml
  - ms-event.yaml
  - ms-social.yaml
  - api-gateway.yaml
  - runners-policies.yaml
  - ws-outbox-policy.yaml
  - ws-service.yaml
