apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: runners-policy
  namespace: prod
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - outbox-user
          - worker-user
          - outbox-post
          - worker-post
          - outbox-event
          - worker-event
          - outbox-social
          - worker-social
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: postgresql
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: redis
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
