apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: dev
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres-access-policy
  namespace: dev
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: postgresql
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchExpressions:
          - key: app
            operator: In
            values:
              - ms-user
              - ms-post
              - ms-event
              - ms-social
              - ws-service
              - post-processor-user
              - post-processor-post
              - post-processor-event
              - post-processor-social
    - podSelector:
        matchLabels:
          app: outbox-runners
    - podSelector:
        matchExpressions:
          - key: app
            operator: In
            values:
              - outbox-user
              - worker-user
              - outbox-post
              - worker-post
              - outbox-event
              - worker-event
              - outbox-social
              - worker-social
              - outbox-ws
    ports:
    - protocol: TCP
      port: 5432

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: neo4j-access-policy
  namespace: dev
spec:
  podSelector:
    matchLabels:
      app: neo4j
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchExpressions:
          - key: app
            operator: In
            values:
              - ms-social
              - post-processor-social
              - worker-social
    ports: 
    - protocol: TCP
      port: 7474
    - protocol: TCP
      port: 7687

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-access-policy
  namespace: dev
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: redis
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchExpressions:
          - key: app
            operator: In
            values:
              - ms-user
              - ms-post
              - ms-event
              - ms-social
              - post-processor-user
              - post-processor-post
              - post-processor-event
              - post-processor-social
    - podSelector:
        matchLabels:
          app: ws-service
    - podSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - outbox-user
          - worker-user
          - outbox-post
          - worker-post
          - outbox-event
          - worker-event
          - outbox-social
          - worker-social
    ports:
    - protocol: TCP
      port: 6379
