apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - traefik/
  - cert-manager/
  - ../namespaces/
  - network-policies/overlays/prod/
  - sealed-secrets/sealed-secrets-app.yaml
  - resource-quotas.yaml
