apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

# Optionnel : On peut augmenter les ressources ici pour la prod si nécessaire
# patches:
#   - target:
#       kind: HelmChart
#       name: ms-user-db
#     patch: |-
#       - op: replace
#         path: /valuesInline/primary/resources/limits/memory
#         value: 512Mi
