apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-service-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws-service-redis
  template:
    metadata:
      labels:
        app: ws-service-redis
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: redis
          image: redis:7-alpine
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            runAsUser: 999
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 6379
              name: redis
          command: ["redis-server"]
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          volumeMounts:
            - mountPath: /data
              name: redis-data
      volumes:
        - name: redis-data
          emptyDir: {}
