apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-service-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws-service-redis
  template:
    metadata:
      labels:
        app: ws-service-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
              name: redis
          command: ["redis-server"]
          args: ["--requirepass", "$(REDIS_PASSWORD)"]
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secrets
                  key: redis-password
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
