apiVersion: v1
kind: Service
metadata:
  name: outbox-ws
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/health"
spec:
  selector:
    app: outbox-ws
  ports:
    - protocol: TCP
      port: 4105
      targetPort: 4105
      name: http
