---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCB6w9YJxOAA4OoeUv2bYFcSqfadD5439JyaldPQj96CbZQ/iGA4rh4EGiDJ1ls9xvFYljntEqotVulgNkfB03eDAZ6j+psRJPjDOciTrN6G6Pv30UupqWn1Wt9KSo312t28m8YN1lNuyU/gpkfPLAL3N4MFCYkhkMea2pxu54MTX3FC1Ytd+cWPa2C/pEaD/4AbjZ8hX8gd780I5P2j4yQBP15OoVaQrf7/F0NyLua6L6rUVZtTgSTr4jQJ0Opl1ipD2mMCJptYS4Q/bmfHnVjjYmjdNhVu274Aek3ivK+cJD5q86uf3BJ6I+DxNVz91tqNpYxH3Qf0DSdXKm87Or7S1fe1f/+Fbk6rZWVIX5n05eswhyJPZy2k5HAJR6PkuZSASxuBy7d8FjQKJZJu7fhpkK846PXc638eA+bi82hWvHU39fn/4qd9ogKwzpbTqHVXbzacN4WpZ1eUdQxGzQyM15sJHGPMBlI7AqP729sdQI7/xa8nM9SpggKl/Z6z1o9WDroXYpJJd5R63cO8y/UTruZx2YfqbgfOoRdYeh4+JCe4Y/mdOYI+j/HC+ig/h/PmiNo3wQ6xHD1pC/1sRtIsls4R6z1+X21sH18nsjv/idPIWmmSJQhwzpmh17MascZ68Kf4G3wr7C18JUoNVia0Q10i748PDsVumup3CgoSf20S8tQIJ8Q2njEYe/LL/YQoVR62dZNhCRnIrxKBQA2lnlrrBG4iiSyZap+zUxCjx4Ym5FGvW8CFJce+YD5zXZuqhvrJQ==
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
