apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/ms-social
  - ../../../../infrastructure/databases/ms-social
  - ../../../../infrastructure/databases/neo4j

namespace: prod

helmCharts:
  - name: postgresql
    repo: https://charts.bitnami.com/bitnami
    releaseName: ms-social-db
    version: 15.5.30
    valuesInline:
      image:
        registry: docker.io
        repository: library/postgres
        tag: 16-alpine
      auth:
        existingSecret: db-secrets
        secretKeys:
          passwordKey: ms-social-password
      primary:
        persistence:
          storageClass: local-path
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        extraVolumes:
          - name: postgresql-run
            emptyDir: {}
          - name: tmp
            emptyDir: {}
        extraVolumeMounts:
          - name: postgresql-run
            mountPath: /var/run/postgresql
          - name: tmp
            mountPath: /tmp
  - name: neo4j
    repo: https://neo4j.github.io/helm-charts
    releaseName: neo4j
    version: 5.20.0
    valuesFile: ../../../../infrastructure/databases/neo4j/neo4j-values.yaml
