apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/ms-social
  - ../../../../infrastructure/databases/ms-social
  - ../../../../infrastructure/databases/neo4j

namespace: prod
