apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Force cache invalidation v3: 2026-05-16T15:26:00Z

resources:
  - ../../../base/ms-social
  - ./db-postgres
  - ./db-neo4j

namespace: prod
