apiVersion: v1
kind: Service
metadata:
  name: post-processor-event
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/health"
spec:
  selector:
    app: post-processor-event
  ports:
    - protocol: TCP
      port: 4203
      targetPort: 4203
      name: http
