apiVersion: v1
kind: Service
metadata:
  name: worker-event
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/health"
spec:
  selector:
    app: worker-event
  ports:
    - protocol: TCP
      port: 4103
      targetPort: 4103
      name: http
