apiVersion: v1
kind: Service
metadata:
  name: outbox-event
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/health"
spec:
  selector:
    app: outbox-event
  ports:
    - protocol: TCP
      port: 4104
      targetPort: 4104
      name: http
