apiVersion: v1
kind: Service
metadata:
  name: ms-event
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/health"
spec:
  selector:
    app: ms-event
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
