apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-ms-event
  namespace: argocd
spec:
  project: prod-project
  source:
    repoURL: https://github.com/Volontariapp/deploy.git
    path: apps/overlays/prod/ms-event
    targetRevision: 36f88c53e8bd9b9d92fd69b0d7a7ce83883b4698
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
