apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-ms-post
  namespace: argocd
spec:
  project: prod-project
  source:
    repoURL: https://github.com/Volontariapp/deploy.git
    path: apps/overlays/prod/ms-post
    targetRevision: 6e213d8007b4bcfee388654604f2e004554588ce
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
