apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-ms-post
  namespace: argocd
spec:
  project: prod-project
  source:
    repoURL: https://github.com/Volontariapp/deploy.git
    path: apps/overlays/prod/ms-post
    targetRevision: c3d67014caab6ddd32c7c48ed74abc43d7d30f4c
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
