apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-ms-post
  namespace: argocd
spec:
  project: prod-project
  source:
    repoURL: https://github.com/Volontariapp/deploy.git
    path: apps/overlays/prod/ms-post
    targetRevision: 2c17d38ba7fe91320632fb28a10020c293f38140
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
