apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-ms-social
  namespace: argocd
spec:
  project: prod-project
  source:
    repoURL: https://github.com/Volontariapp/deploy.git
    path: apps/overlays/prod/ms-social
    targetRevision: 790d5449643c1541c86ee88984c59dc2b372cc87
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
