apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-ms-user
  namespace: argocd
spec:
  project: prod-project
  source:
    repoURL: https://github.com/Volontariapp/deploy.git
    path: apps/overlays/prod/ms-user
    targetRevision: 5e1fcce6d1acdaa070348a7630d483ce6a23d632
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
