apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-databases
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: prod-project
  source:
    repoURL: https://github.com/Volontariapp/deploy.git
    path: infrastructure/databases/overlays/prod
    targetRevision: HEAD
    kustomize:
      buildOptions: "--enable-helm"
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  ignoreDifferences:
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/externalTrafficPolicy
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/volumeClaimTemplates
