apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-ws-service
  namespace: argocd
spec:
  project: prod-project
  source:
    repoURL: https://github.com/Volontariapp/deploy.git
    path: apps/overlays/prod/ws-service
    targetRevision: 9be527d85fcf3c010cb98f2bd82af3a2ee0c438a
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
