apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-api-gateway
  namespace: argocd
spec:
  project: dev-project
  source:
    repoURL: https://github.com/Volontariapp/deploy.git
    path: apps/overlays/dev/api-gateway
    targetRevision: e2fd3ad52a4d051f398443db1346219abd433800
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
