apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-ms-event
  namespace: argocd
spec:
  project: dev-project
  source:
    repoURL: https://github.com/Volontariapp/deploy.git
    path: apps/overlays/dev/ms-event
    targetRevision: 5e1fcce6d1acdaa070348a7630d483ce6a23d632
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
