apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-ms-post
  namespace: argocd
spec:
  project: dev-project
  source:
    repoURL: https://github.com/Volontariapp/deploy.git
    path: apps/overlays/dev/ms-post
    targetRevision: fb2dc2618dac39ab3f7571d328ec9f70a5a70c31
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
