apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-ms-social
  namespace: argocd
spec:
  project: dev-project
  source:
    repoURL: https://github.com/Volontariapp/deploy.git
    path: apps/overlays/dev/ms-social
    targetRevision: 2c17d38ba7fe91320632fb28a10020c293f38140
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
