apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-ms-social
  namespace: argocd
spec:
  project: dev-project
  source:
    repoURL: https://github.com/Volontariapp/deploy.git
    path: apps/overlays/dev/ms-social
    targetRevision: 21fdb50fddd5b7a783a38a01ed6a8329b4fa047d
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
