apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-ms-user
  namespace: argocd
spec:
  project: dev-project
  source:
    repoURL: https://github.com/Volontariapp/deploy.git
    path: apps/overlays/dev/ms-user
    targetRevision: 2d5507655693d5fb972e511eb9e8879cb061ceb8
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
