apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-ws-service
  namespace: argocd
spec:
  project: dev-project
  source:
    repoURL: https://github.com/Volontariapp/deploy.git
    path: apps/overlays/dev/ws-service
    targetRevision: 9be527d85fcf3c010cb98f2bd82af3a2ee0c438a
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
