apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 7474
        fsGroup: 7474
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: neo4j
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            runAsUser: 7474
            seccompProfile:
              type: RuntimeDefault
