---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-login
  namespace: prod
spec:
  encryptedData:
    .dockerconfigjson: AgAFA14HHCQQlsx411/T8Apfjp95jKqVr8OCPRRf0mGMZ+pT1rl8rp8bumC17MbqV5JimmCWMN6yZ6TrzljtHYbu3r1Dk4uVOfZHEgTBIKWA2QIzMeHfgmjVxJ4gYNJB5LkbyeVSecMpIvmQdKrokwcYU6OLwUqpAcnAYCDy7HKIMMxZuSpOHOBZqncYfs5V9sF84kWuoM2gxiyvyPGsLN7tHHxU/i/MxVo0JJoEsAOJOP3V5BOd30eyhF5k2bsvDzl42UOb3NxnQdz6ImzUOvjs2RE9utbNyn6RnIGhqg/PW7RICRLwlKdQ8lLM9gRbxeQMmjDZtM3LO1mQoKYZkf+8HwERcectLuJZ/VWq2uTX1D1zdcO6AXE1jZd/E7CyQ4C/FmK8/WemldQI2SLkB+QRo3eyiEBDRYCt4xn7L/nyLWbnPtWS38JgLe2EcqOzf0AjOtsyV3Z/JT5/pKOxhTMAu1YlaBtFBhFOQ1Ba93cTwhhjV1gSWhI7sd6O33aA10/cxHZiIpHQnpkLvAe1goxVmUs+W57mQNhvZwoxeTO0H9ko1hHuuirO8iqt3XPfC76d3O+LP3MUGZvRjzIJ63UoUd5mOyVULKVbCCxhpwUAlDIZDbqpkFXyZmOucou1kt+18xsaYznrHUokTYz3UxlFEsMGGbzmyS0BlBzoghA0u6JgUmqe7II5aNAFQ694C41+9hkdykErcGL2fbXtnnQN8dr3AtVOKi3glJi7OHQIEokg57pN3xJVuj/t94tW6V0xjAcLf0dFWR5Vf1fZE4BxssbVLodEv3M0of5Zx5BODeueawjPVEI2IvHVRn4DVXHHKoqNC4Wg04OrKQq6LvgusVJnfjWgAgpUGlUdvJhwu73pA09vsek9thUzrfWZdqyrzOCh2QaXL5+1Mhvv5oftrRvyauj0c22eMOK67xSOKr/OykDNqd8SrSmZzOUgyhs9cIdtwAAf
  template:
    metadata:
      name: ghcr-login
      namespace: prod
    type: kubernetes.io/dockerconfigjson
