---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-login
  namespace: prod
spec:
  encryptedData:
    .dockerconfigjson: AgCz1bPOqb7kkpdCIrtfQ0BbMDBzONEIIqiX4Bp0xkyX8n48PFUeyy3haSch/rUJzMbuqcgWGT5RydL3ioJ3DuYag3HqHQfGlLPnihG1Qu7l7ZjBMjcE2rCvkW06CJoyqneKPZZtTXDzkATH4WHyUfPLmRfcWFF7fQWGrqO/Urrx9mJIGCr9QOBEiCH2CEM1YhcGyRGaPFtdi/aVVH3YbFbAbF3eEmGrQDZm1Hd6bznwhzacG1TYpKcqVXvOQfZGammjkfq3FCrN3laz8q++P0tDWNgEC7Y9fPEpEXPVqQ2qRy8G3Pi19h1PBqVzpGznZyO0CXjq5n+jtRtca3olS6xKhq8H8AvNYwBv2oNasNEiw4Rrcvhf6B+u/LAQRqj8U9cu1AFRgLQKpgxotgnN4mPLG1Ob6APvn6hCMsOZ1CB5pJnkV6VERWYSQfsxHJecYuA+r8kNChkTx0nHAqveOHmQiQ71IYrjcbChPZPVKzBtxelUzFCrkU/X/IuyGNN63ckINwJO0eqd2U26PTHPcO3F9UVD3PaD4cF0Lu0Cy5ip9mgCutTp8qExE/Q3M0DwcVTACGjS+ddqYXqbXchR1eB4HDCvt6bQzTkLn0MTS/Dzh6VLHWg0xBBu5X/DNPlJeWtuga0Ij8FCHng/Z5Px3miBVdBtENg/sKrEIUwbShqPB9LFblLZlqgPyrHrBOjwaeU0Ao6548+b6q7b6SU26kcl4MSImqkI5/2dAUlSOlt7VFEfWz0if8ZaH//3ZheV+YtiGH4knnDZ0qxNccCduMhCPqI8xy1Mz62SMGkP+Pf8Jwnvq4vDunhEARx/ZRTiwgoSVsg6+43gqhIZqqdTeh7Ja0jhBfoqGZJRJbe3FqqQgvVkHXX/hzbt+4xPIxCCKtUgHKcuLoEI0vuhvjkjHaWIxi0lV837y/POwmfh4PXF7GZ2A69eoFbG
  template:
    metadata:
      name: ghcr-login
      namespace: prod
    type: kubernetes.io/dockerconfigjson
