apiVersion: v1
kind: Service
metadata:
  name: outbox-post
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/health"
spec:
  selector:
    app: outbox-post
  ports:
    - protocol: TCP
      port: 4103
      targetPort: 4103
      name: http
