apiVersion: v1
kind: Service
metadata:
  name: post-processor-post
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/health"
spec:
  selector:
    app: post-processor-post
  ports:
    - protocol: TCP
      port: 4204
      targetPort: 4204
      name: http
