apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: postgresql
    repo: https://charts.bitnami.com/bitnami
    releaseName: ms-event-db
    version: 15.5.30
    valuesInline:
      image:
        registry: docker.io
        repository: postgis/postgis
        tag: 16-3.4
      auth:
        database: ms-event
        username: ms-event
        existingSecret: db-secrets
        secretKeys:
          userPasswordKey: ms-event-password
      primary:
        persistence:
          storageClass: local-path
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        extraVolumes:
          - name: postgresql-run
            emptyDir: {}
        extraVolumeMounts:
          - name: postgresql-run
            mountPath: /var/run/postgresql
