---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: datadog-keys
  namespace: datadog
spec:
  encryptedData:
    api-key: AgAeZxrCZT0d/o2XDzAkQWSVpQ801ZlSescG6eFzKgErOLAmmS5nQt7leu8+qf3h9GZqk6XtbT+SmH5eyIUkU6ZZx/w0kET4z4qs84Qb0XNJegIyNGzT7uyRYPdq+ReTmw0jhzaY6H1aoLnOHb51nda90f5dsHwFsURDillR784deEU7ACl/tDexq4hCuOPJDhQGU+gTSiIv5uqJ46EoxyyVITSR8un1haRaru+qKyugSpdPS5JMxiCQgdLLxepbBHZCGlwm6gDzGVY5DtOgbSGJrA56Jyjdgw0DBg9EP3z3N7LztGmO4/npNjNxKw5yq4z4tMy0WVzsmad9OfhtGPAO1RFcE7XtiE3YIO2u1Yrlj3Bmjm8XgTlkKg/3asGqaqa/gHfc5IMmKcUS7zjI+kMCSHWrxuLnMOLvZIjm++7+jXbzxSVLxzTMk/yokXCAGfPueLGyZGnnuAkfCgx8wdzohJNU8G1xr/AcvBjwJVh5KlAuFO0Ql739zu1ARTB2s/Li+hps96ZLAfj3nm4D+m2ceVWGJRzTogPMbB620m0PKM8RxezEdPbqvyHmtzgOu9St/crHnf6n63KtOw1rCv9Nze8uZb7psKhHoHO+WxuZ0JS3W326FtLqs5SQn/KfP4bRyFxTyqo/y47hxGzgBXfvnkDIrAKcnuchFYeCXzC1WlMQIJv+RgmnpPXtiJchRQuhALqUYzcEJYUQee3uo2qPMejEENLxMTVhjCXbugCuaw==
  template:
    metadata:
      name: datadog-keys
      namespace: datadog
