---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: datadog-keys
  namespace: datadog
spec:
  encryptedData:
    api-key: AgBC38fXDxrXNo30X0nKU7TgU507IJfEvOfk6FVM6+gbnvEyIoQzNiooNdYbVouVGbszun0V1eAmkW+mz2B9EPdAatFJZx2aJoD7zu6BixiOn8dLumA+6bj2Q5g7tMIzSEWEprN53iydMnGOMAmEv2ELSvgNvC/iYrrOFDHnoHt5KTxRiYb86BKjWtntm70uxWtR8IGN70+IhzTaSi+TfJChKPPVEko5LFaCiu7Jbdy++OjB4wzL2+sPCD0rQph+JuFEiJpMwRu5tlnY8DhyO+G+wvwDz2sJX1YHGr6KMUUozfa5mJsOyjazx/0hGj3W/QmFl6/FcTRrnkhFRXhB2IVH85MvEPOZJJqEcmh7H2qJHjTTUG6iXXuv8nV6R9Hcon+49aH9lOlKo/smNd1bw31vIwjD2eCJsA2NIRUF6K007I9tqRmDQ3AVPVjBE/8tQmUJsyfnQ6x6Bj2KZ25q4DT1ggyUtwAFsVC6HmWaMoXGT/wfXMEgqT6Tg/wkoJkhXZAM89MVs1puIWED7zcNQ1lQO9QNbg2HNyK1dqVtQzB/y0neE7N7+xRXFC+KNenVRxLqDlRx1pakg6W1DpbumZWuMXqyfP9jUXmUSlI5SJ6X9x3V2Tu8BjT7zTCBd9yTy/xiQSWL/gMr+WhnT4tjJ6pDdQj5loPS8TZPiv9ixKWB+Dw7JX40GV1CUawLZ98t9jNMgroQZmnAxNxQdEEVwKgAbPJEam5zYpzZ6wyeEn0vRw==
  template:
    metadata:
      name: datadog-keys
      namespace: datadog
