apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog-agent-install
  namespace: argocd
spec:
  project: default
  source:
    chart: datadog
    repoURL: https://helm.datadoghq.com
    targetRevision: 3.245.1
    helm:
      values: |
        datadog:
          site: us5.datadoghq.com
          clusterName: volontariapp-cluster
          apiKeyExistingSecret: datadog-keys
          kubeStateMetricsEnabled: true
          
          otlp:
            receiver:
              protocols:
                grpc:
                  enabled: true
                  endpoint: "0.0.0.0:4317"
                  # useHostPort: true est activé par défaut par Datadog, ce qui expose le port 4317
          
          secretBackend:
            command: "/readsecret_multiple_providers.sh"
            enableGlobalPermissions: true
            
          logs:
            enabled: false # TODO: Enable logs phase 3
        agents:
          containers:
            agent:
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                limits:
                  cpu: 500m
                  memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: datadog
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
