apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-processor-user
  labels:
    app: post-processor-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-processor-user
  template:
    metadata:
      labels:
        app: post-processor-user
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      imagePullSecrets:
        - name: ghcr-login
      initContainers:
        - name: wait-for-db
          image: busybox:1.28
          command: ['sh', '-c', "until nc -zv ms-user-db-postgresql 5432; do echo waiting for db; sleep 2; done"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 32Mi
        - name: wait-for-redis
          image: busybox:1.28
          command: ['sh', '-c', "until nc -zv redis-master 6379; do echo waiting for redis; sleep 2; done"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 32Mi
      containers:
        - name: post-processor-user
          image: ghcr.io/volontariapp/post-processor-user:sha-a87309e
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            runAsUser: 1001
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 4202
              name: http
          env:
            - name: NODE_ENV
              value: "production"
            - name: POST_PROCESSOR_BATCH_SIZE
              value: "10"
            - name: PORT
              value: "4202"
            - name: DB_HOST
              value: "ms-user-db-postgresql"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "ms-user"
            - name: DB_USERNAME
              value: "ms-user"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: ms-user-password
            - name: REDIS_HOST
              value: "redis-master"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: redis-password
          resources:
            limits:
              cpu: 50m
              memory: 96Mi
            requests:
              cpu: 10m
              memory: 48Mi
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: tmp-volume
          emptyDir: {}
