apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - deployment-outbox.yaml
  - deployment-worker.yaml

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/revisionHistoryLimit
        value: 2
