apiVersion: v1
kind: Service
metadata:
  name: worker-user
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/health"
spec:
  selector:
    app: worker-user
  ports:
    - protocol: TCP
      port: 4102
      targetPort: 4102
      name: http
