apiVersion: v1
kind: Service
metadata:
  name: post-processor-user
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/health"
spec:
  selector:
    app: post-processor-user
  ports:
    - protocol: TCP
      port: 4202
      targetPort: 4202
      name: http
