apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-login
  namespace: prod
spec:
  encryptedData:
    .dockerconfigjson: <REPLACE_WITH_ENCRYPTED_DOCKERCONFIGJSON>
  template:
    type: kubernetes.io/dockerconfigjson
    metadata:
      name: ghcr-login
      namespace: prod
