apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ghcr-sealed-secret.yaml

namespace: prod

images:
  - name: ms-user
    newName: ghcr.io/volontariapp/ms-user
  - name: ms-post
    newName: ghcr.io/volontariapp/ms-post
  - name: ms-event
    newName: ghcr.io/volontariapp/ms-event
  - name: ms-social
    newName: ghcr.io/volontariapp/ms-social

