apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ghcr-sealed-secret.yaml
  - ws-service

namespace: prod

images:
  - name: volontariapp/ms-user
    newName: ghcr.io/volontariapp/ms-user
  - name: volontariapp/ms-post
    newName: ghcr.io/volontariapp/ms-post
  - name: volontariapp/ms-event
    newName: ghcr.io/volontariapp/ms-event
  - name: volontariapp/ms-social
    newName: ghcr.io/volontariapp/ms-social
  - name: volontariapp/ws-service
    newName: ghcr.io/volontariapp/ws-service

