name: 'Lint & Security Scan'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gitleaks Scan
        run: |
          docker run --rm -v $(pwd):/path zricethezav/gitleaks:latest detect --source="/path" --verbose --redact

      - name: Validate Databases Overlays
        run: |
          kustomize build infrastructure/databases/overlays/dev --enable-helm > /dev/null
          kustomize build infrastructure/databases/overlays/prod --enable-helm > /dev/null

      - name: Validate Apps Overlays
        run: |
          kustomize build apps/overlays/dev --enable-helm > /dev/null
          kustomize build apps/overlays/prod --enable-helm > /dev/null

      - name: Kube-score Scan
        run: |
          kustomize build infrastructure/databases/overlays/prod --enable-helm > prod-full.yaml
          echo "---" >> prod-full.yaml
          kustomize build infrastructure/security/network-policies/overlays/prod --enable-helm >> prod-full.yaml

          docker run --rm -v $(pwd):/project zegl/kube-score:latest score prod-full.yaml \
            --ignore-test container-resources \
            --ignore-test networkpolicy-targets-pod \
            --ignore-test pod-networkpolicy \
            --ignore-test container-image-pull-policy \
            --ignore-test container-ephemeral-storage-request-and-limit \
            --ignore-test container-security-context-user-group-id \
            --ignore-test container-security-context-readonlyrootfilesystem \
            --ignore-test pod-probes-identical \
            --ignore-test statefulset-has-servicename
