apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: neo4j
    repo: https://neo4j.github.io/helm-charts
    releaseName: neo4j
    version: 5.20.0
    valuesFile: neo4j-values.yaml

patches:
  - path: neo4j-patch.yaml
    target:
      kind: StatefulSet
      name: neo4j
patchesJson6902:
  - target:
      kind: Service
      name: neo4j-lb-neo4j
    patch: |-
      - op: replace
        path: /spec/type
        value: ClusterIP
      - op: remove
        path: /spec/externalTrafficPolicy
